package rosalind.teman;

public class FindingMotifDNA {

	public static void main(String[] args) {
		
		String DNA = "TGGGGCCGATTTAAAGGCCGATGGTACTGGGGGCCGATTAGACGAAGATGGGCCGATGGCCGATGGCCGATCTGGCCGATCGGCCGATGGCCGATAGAGGCCGATCTAAGGCCGATATCCGGCCGATGGCCGATGGCCGATCAGTCGGCCGATCGCGGCCGATTGTGGCCGATAAACTTAGCTCGAAAATCCTTGGGCCGATCCAGGCCGATGGCCGATGGCCGATAAGGCCGATAAGGGCCGATGGCCGATCTTAAGCCACGGCCGATGGCCGATGGCCGATGAATGCGGGGCCGATTGGCCGATTAGGCCGATTCTGGCCGATGCAAGGGCCGATGGCCGATGGCCGATGTACCGGCCGATTAGGCCGATCGGCCGATTGCAAAAAGGCCGATTCTTGGGTAGCACTTGGAGATATATTCGGCCGATAAGGGCCGATGGCCGATGGCCGATAAAGGCCGATCTAAGGCCGATGTGGCCGATGGCCGATTAGTAACGGCCGATCTGGCCGATAAAACTCACCTTGGCCGATTACAGGTCAAGGCCGATGGGCCGATCGGCCGATTCTCCGGCCGATTGGCCGATTCGCGTGGCCGATGGCCGATGGCCGATGGCTGGGCCGATTCTACTGGCCGATTGGGCCGATTGGCCGATACACAGGCCGATAGGCCGATTAATGGGCCGATGGGCCGATAAAGGCCGATACGGCCGATGGCCGATAGGGGCCGATCAGAATGGCCGATCAGGCCGATGGCCGATGCGGGCCGATTGGCCGATGGCCGATTGGCCGATGGCCGATGATTGGGCCGAT";
		String t = "GGCCGATGG";
		int pos = DNA.indexOf(t, 0);
		while(pos != -1){
			System.out.print(pos+1 + " ");
			pos = DNA.indexOf(t,pos+1);
		}
	}
}
